#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mvn-xom
Version  : 10
Release  : 1
URL      : https://github.com/elharo/xom/archive/XOM_10.tar.gz
Source0  : https://github.com/elharo/xom/archive/XOM_10.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-1.1 LGPL-2.1 Public-Domain W3C-19980720
BuildRequires : apache-ant
BuildRequires : buildreq-mvn

%description
XOM is a library. By itself, it doesn't do much of anything. It exists
only to be used by other programs. It requires Java 1.2 or later.

%prep
%setup -q -n xom-XOM_10

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export ANT_HOME=/usr/share/ant
ant -d -v
%install


%files
%defattr(-,root,root,-)
